import logging
from enum import Enum
from typing import Union

import pandas  # type: ignore[import]

class DataRequest(Enum):
    Expanded = ...
    Standard = ...
    Velos = ...

class REDCapInterface:
    def __init__(self, isdev: bool = ..., timeout_sec: int = ...) -> None:
        self.__api_uri: str = None
        self.__capmc_token: str = None
        self.__discard_empty_fields = None
        self.__isdev: bool = None
        self.__log: logging.Logger = None
        self.__timeout_sec: int = None
        self.__valid: bool = None
        ...
    def create(
        self, data_records: Union[dict, pandas.DataFrame], overwrite: bool = False
    ) -> bool: ...
    def delete(self, record_number: int) -> bool: ...
    def exists(self, record_number: int) -> bool: ...
    def last_record_number(
        self, except_for: Union[int, list, None] = ..., number_desired: int = ...
    ) -> Union[int, list]: ...
    def next_record_number(self) -> int: ...
    def __read_config_file(self) -> None: ...
    def report(self, report_id: Union[int, str]) -> pandas.DataFrame: ...
    def retrieve(
        self,
        record_numbers: Union[int, list, None] = ...,
        data_request: DataRequest = ...,
    ) -> pandas.DataFrame: ...
    def update(self, new_data_records: Union[dict, pandas.DataFrame] = ...) -> bool: ...
    def version(self) -> str: ...
    def __known_test_record_present(self) -> bool: ...
    def __build_data_pull(
        self, record_numbers: Union[list, None], expanded_record: bool
    ) -> dict: ...
    def __path_to_secrets(self) -> str: ...
    def __update_one_record(
        self, new_data_record: dict, existing_record: pandas.DataFrame
    ) -> bool: ...
