import pandas  # type: ignore[import]
from typing import Union

class REDCapInterface:
    def __init__(self, isdev: bool = ..., timeout_sec: int = ...) -> None: ...
    def create(self, data_records: Union[dict, pandas.DataFrame]) -> bool: ...
    def delete(self, record_number: int) -> bool: ...
    def exists(self, record_number: int) -> bool: ...
    def last_record_number(
        self, except_for: Union[int, list, None] = ..., number_desired: int = ...
    ) -> Union[int, list]: ...
    def next_record_number(self) -> int: ...
    def retrieve(
        self, record_numbers: Union[int, list, None] = ..., expanded_record: bool = ...
    ) -> pandas.DataFrame: ...
    def update(self, new_data_records: Union[dict, pandas.DataFrame] = ...) -> bool: ...
    def version(self) -> str: ...
