import logging
from enum import Enum

import pandas

class DataRequest(Enum):
    Expanded = 1
    Standard = 2
    Velos = 3

class REDCapInterface:
    def __init__(
        self, isdev: bool = ..., timeout_sec: int = ..., test_mode: bool = ...
    ) -> None:
        self.__api_uri: str = ...
        self.__capmc_token: str = ...
        self.__isdev: bool = ...
        self.__log: logging.Logger = ...
        self.__timeout_sec: int = ...
        self.__valid: bool = ...
        ...

    def create(
        self, data_records: dict | pandas.DataFrame, overwrite: bool = False
    ) -> bool: ...
    def delete(self, record_number: int) -> bool: ...
    def __discard_empty_fields(self, input_dict: dict) -> dict: ...
    def exists(self, record_number: int) -> bool: ...
    def last_record_number(
        self, except_for: int | list | None = ..., number_desired: int = ...
    ) -> int | list: ...
    def next_record_number(self) -> int: ...
    def __read_config_file(self) -> None: ...
    def report(self, report_id: int | str) -> pandas.DataFrame: ...
    def retrieve(
        self,
        record_numbers: int | list | None = ...,
        data_request: DataRequest = ...,
    ) -> pandas.DataFrame: ...
    def update(self, new_data_records: dict | pandas.DataFrame = ...) -> bool: ...
    def version(self) -> str: ...
    def __known_test_record_present(self) -> bool: ...
    def __build_data_pull(
        self,
        record_numbers: list | None,
        data_request: DataRequest = DataRequest.Standard,
    ) -> dict: ...
    def __update_one_record(
        self, new_data_record: dict, existing_record: pandas.DataFrame
    ) -> bool: ...
